name: Update Bluesky Field

on:
  push:
    branches: [main]

jobs:
  update-bluesky:
    runs-on: ubuntu-latest
    steps:
      - name: Wait 5 minutes for Bridgy to post
        run: sleep 300

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios gray-matter

      - name: Update bluesky field
        run: node .github/scripts/update-bluesky.js

      - name: Commit and push changes
        run: |
          git config user.name "lukecarbis"
          git config user.email "luke@carb.is"
          git add content/posts/*.md
          git commit -m "Auto update Bluesky field"
          git push
        continue-on-error: true